---
- hosts: metrics_source
  become: yes
  vars:
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    metric_store_ip: 172.31.29.28
  tasks:
    - name: "install telegraf"
      yum:
        name: "{{telegraf_url}}"
        state: present
    - name: "copy cfg into dest"
      template:
        src: templates/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
    - name: "start telegraf"
      service:
        name: "telegraf"
        state: restarted
- hosts: metrics_store
  become: yes
  vars:
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
  tasks:
    - name: "install influx"
      yum:
        name: "{{influxdb_url}}"
        state: present
    - service:
        name: influxdb
        state: started
- hosts: metrics_graph
  become: yes
  vars:
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
  tasks:
    - yum:
        name: "{{grafana_url}}"
        state: present
    - service:
        name: "grafana-server"
        state: started